"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['thelist-crawler.py']
DATA_FILES = ['logo.jpg', 'logo.png']
OPTIONS = {
    'argv_emulation': True,
    'iconfile':'logo.icns'
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app', 'selenium', 'Pillow', 'PyMySQL'],
)
